version: '3'
services:
  web:
    image: agungbhaskara/lms-belajar-docker:1.3
    build:
      context: .
      dockerfile: dockerfile
    container_name: lms-belajar-docker-app
    env_file:
      - .env
    ports:
      - "1234:1234"
  db:
    container_name: lms-belajar-docker-db
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      DB_NAME: docker_database1
    ports:
      - "3307:3306"