name: test,build,deploy app
# set trigger actions to active
on:
  push:
    branches:
      - master
# what doing job execute when actions
jobs:
  build-docker:
    name: build and push to docker registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: docker build
        run: docker build -t agungbhaskara/ci-cd-project:latest .

      - name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: push docker
        run: docker push agungbhaskara/ci-cd-project:latest
