name: test,build,deploy app
# set trigger actions to active
on:
  push:
    branches:
      - master
# what doing job execute when actions
jobs:
  build-docker:
    name: build and push to docker registry
    runs-on: ubuntu-latest
    env:
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_NAME: ${{ secrets.DB_NAME }}
      SECRET_KEY: ${{ secrets.AUTH_KEY }}
    steps:
      - uses: actions/checkout@v3
      - name: docker build
        run: |
          docker build -t agungbhaskara/ci-cd-project:latest \
            --build-arg DB_USER=${DB_USER} \
            --build-arg DB_PASSWORD=${DB_PASSWORD} \
            --build-arg DB_HOST=${DB_HOST} \
            --build-arg DB_PORT=${DB_PORT} \
            --build-arg DB_NAME=${DB_NAME} \
            --build-arg SECRET_KEY=${SECRET_KEY} \
            .

      - name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: push docker
        run: docker push agungbhaskara/ci-cd-project:latest
  deploy:
    name: deployment to server
    env:
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_NAME: ${{ secrets.DB_NAME }}
      SECRET_KEY: ${{ secrets.AUTH_KEY }}
    runs-on: ubuntu-latest
    needs: build-docker
    steps:
      - name: SSH and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_SERVER_HOST }}
          key: ${{ secrets.SSH_SERVER_KEY }}
          username: ${{ secrets.SSH_SERVER_USERNAME }}
          script: |
            whoami

            docker pull agungbhaskara/ci-cd-project:latest
            docker stop go-ci-cd-app || true
            docker rm go-ci-cd-app || true

            docker run -d -p 1234:1234 --name go-ci-cd-app \
              --e DB_USER=${DB_USER} \
              --e DB_PASSWORD=${DB_PASSWORD} \
              --e DB_HOST=${DB_HOST} \
              --e DB_PORT=${DB_PORT} \
              --e DB_NAME=${DB_NAME} \
              --e SECRET_KEY=${SECRET_KEY} \
              agungbhaskara/ci-cd-project:latest
